cc_library(
    name = "muduo_base",
    srcs = ["CountDownLatch.cpp", "Thread.cpp"],
    hdrs = ["CountDownLatch.h", "Thread.h", "CurrentThread.h", "noncopyable.h"],
    visibility = ["//net:__pkg__", "//net/test:__pkg__"],
)